version: '3.1'

services:
  postgres:
    container_name: blog_seo_backend_postgres_container
    image: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-superpwd}
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped

  db-test:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test-pwd}
      POSTGRES_DB: test
    ports:
      - '54321:5432'

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
