version: '3.1'

services:
  postgres:
    container_name: blog_seo_backend_postgres_container
    image: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-superpwd}
      POSTGRES_DB: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
